### ISSUE TITLE
AsyncMessage used_gas

### ISSUE THREAD

**Issue by damip** [massalabs/massa-proto-rs#27]
In the AsyncMessage object, it should not be `used_gas` but `max_gas`

**Comment by aoudiamoncef** [comment]
Hi @damip 

It already the case https://github.com/massalabs/massa-proto-rs/blob/09870a9d6590e5e67e9b16dd427efef3c5bbe4a6/src/massa.model.v1.rs#L973C9-L973C17

This was fixed by #4324

**Comment by aoudiamoncef** [comment]
> In the link you sent it is used_gas. But used_gas should only be for execution results, not for async messages where it should be max_gas

Sorry, my brain still in holidays... I'll fix this

**Comment by damip** [comment]
Yes I think that's the only place
